/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation(project(":api"))
    implementation(project(":builder"))
    implementation("org.mandas.kafka:kafka-cluster-unit:2.4.0")
}